export const atribuicoes = {
  Ourinhos: [
    {
      nome: "João",
      funcao: "Eletricista",
      presenca: true,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
      entrada: "08:12",
    },
    {
      nome: "Mário",
      funcao: "Encanador",
      presenca: false,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
      entrada: "08:14",
    },
    {
      nome: "Deilton",
      funcao: "Eletricista",
      presenca: true,
      local: "Ourinhos",
      horario: "08:00 - 15:00",
      entrada: "08:16",
    },
    {
      nome: "Antônio",
      funcao: "Pintor",
      presenca: false,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
      entrada: "08:18",
    },
    {
      nome: "Carlos",
      funcao: "Pedreiro",
      presenca: true,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
      entrada: "08:20",
    },
    {
      nome: "Paulo",
      funcao: "Encanador",
      presenca: true,
      local: "Ourinhos",
      horario: "09:00 - 18:00",
      entrada: "09:12",
    },
    {
      nome: "Luiz",
      funcao: "Eletricista",
      presenca: false,
      local: "Ourinhos",
      horario: "09:00 - 18:00",
      entrada: "09:14",
    },
    {
      nome: "Fernando",
      funcao: "Pintor",
      presenca: true,
      local: "Ourinhos",
      horario: "09:00 - 18:00",
      entrada: "09:16",
    },
    {
      nome: "Gustavo",
      funcao: "Pedreiro",
      presenca: false,
      local: "Ourinhos",
      horario: "10:00 - 19:00",
      entrada: "10:12",
    },
    {
      nome: "Ricardo",
      funcao: "Encanador",
      presenca: true,
      local: "Ourinhos",
      horario: "10:00 - 19:00",
      entrada: "10:14",
    },
    {
      nome: "José",
      funcao: "Eletricista",
      presenca: true,
      local: "Ourinhos",
      horario: "10:00 - 19:00",
      entrada: "10:16",
    },
  ],
  Canitar: [
    {
      nome: "Felipe",
      funcao: "Eletricista",
      presenca: false,
      local: "Canitar",
      horario: "16:00 - 18:00",
      entrada: "16:12",
    },
    {
      nome: "Deilton",
      funcao: "Pedreiro",
      presenca: false,
      local: "Canitar",
      horario: "16:00 - 18:00",
      entrada: "16:14",
    },
    {
      nome: "Lucas",
      funcao: "Encanador",
      presenca: true,
      local: "Canitar",
      horario: "16:00 - 18:00",
      entrada: "16:16",
    },
    {
      nome: "Anderson",
      funcao: "Eletricista",
      presenca: false,
      local: "Canitar",
      horario: "16:00 - 18:00",
      entrada: "16:18",
    },
  ],
};

export const horarios = [
  {
    nome: "Deilton",
    funcao: "Eletricista",
    presenca: true,
    local: "Ourinhos",
    horario: "08:00 - 12:00",
    dia: "0",
  },
  {
    nome: "Deilton",
    funcao: "Eletricista",
    presenca: false,
    local: "Ourinhos",
    horario: "13:00 - 15:00",
    dia: "0",
  },
  {
    nome: "Deilton",
    funcao: "Eletricista",
    presenca: false,
    local: "Ourinhos",
    horario: "16:00 - 18:00",
    dia: "2",
  },
  {
    nome: "Deilton",
    funcao: "Eletricista",
    presenca: false,
    local: "Canitar",
    horario: "16:00 - 18:00",
    dia: "0",
  },
  {
    nome: "Deilton",
    funcao: "Eletricista",
    presenca: false,
    local: "Canitar",
    horario: "16:00 - 18:00",
    dia: "1",
  },
  {
    nome: "Deilton",
    funcao: "Eletricista",
    presenca: false,
    local: "Canitar",
    horario: "12:00 - 18:00",
    dia: "4",
  },
  {
    nome: "Deilton",
    funcao: "Eletricista",
    presenca: false,
    local: "Ourinhos",
    horario: "07:00 - 15:00",
    dia: "3",
  },
];
