export const atribuicoes = {
  Ourinhos: [
    {
      nome: "João",
      funcao: "pedreiro",
      presenca: true,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
    },
    {
      nome: "Mário",
      funcao: "encanador",
      presenca: false,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
    },
    {
      nome: "Deilton",
      funcao: "eletricista",
      presenca: true,
      local: "Ourinhos",
      horario: "08:00 - 15:00",
    },
    {
      nome: "Antônio",
      funcao: "pintor",
      presenca: false,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
    },
    {
      nome: "Carlos",
      funcao: "pedreiro",
      presenca: true,
      local: "Ourinhos",
      horario: "08:00 - 17:00",
    },
    {
      nome: "Paulo",
      funcao: "encanador",
      presenca: true,
      local: "Ourinhos",
      horario: "09:00 - 18:00",
    },
    {
      nome: "Luiz",
      funcao: "eletricista",
      presenca: false,
      local: "Ourinhos",
      horario: "09:00 - 18:00",
    },
    {
      nome: "Fernando",
      funcao: "pintor",
      presenca: true,
      local: "Ourinhos",
      horario: "09:00 - 18:00",
    },
    {
      nome: "Gustavo",
      funcao: "pedreiro",
      presenca: false,
      local: "Ourinhos",
      horario: "10:00 - 19:00",
    },
    {
      nome: "Ricardo",
      funcao: "encanador",
      presenca: true,
      local: "Ourinhos",
      horario: "10:00 - 19:00",
    },
    {
      nome: "José",
      funcao: "eletricista",
      presenca: true,
      local: "Ourinhos",
      horario: "10:00 - 19:00",
    },
  ],
  Canitar: [
    {
      nome: "Felipe",
      funcao: "eletricista",
      presenca: false,
      local: "Canitar",
      horario: "16:00 - 18:00",
    },
    {
      nome: "Deilton",
      funcao: "pedreiro",
      presenca: false,
      local: "Canitar",
      horario: "16:00 - 18:00",
    },
    {
      nome: "Lucas",
      funcao: "encanador",
      presenca: true,
      local: "Canitar",
      horario: "16:00 - 18:00",
    },
    {
      nome: "Anderson",
      funcao: "eletricista",
      presenca: false,
      local: "Canitar",
      horario: "16:00 - 18:00",
    },
  ],
};

export const horarios = [
  {
    nome: "Deilton",
    funcao: "eletricista",
    presenca: true,
    local: "Ourinhos",
    horario: "08:00 - 15:00",
    dia: "0",
  },
  {
    nome: "Deilton",
    funcao: "pedreiro",
    presenca: false,
    local: "Ourinhos",
    horario: "16:00 - 18:00",
    dia: "1",
  },
  {
    nome: "Deilton",
    funcao: "pedreiro",
    presenca: false,
    local: "Ourinhos",
    horario: "16:00 - 18:00",
    dia: "2",
  },
  {
    nome: "Deilton",
    funcao: "pedreiro",
    presenca: false,
    local: "Canitar",
    horario: "16:00 - 18:00",
    dia: "0",
  },
  {
    nome: "Deilton",
    funcao: "pedreiro",
    presenca: false,
    local: "Canitar",
    horario: "16:00 - 18:00",
    dia: "1",
  },
];
